import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Landing from "~/components/pages/Landing";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Spotify Huddles</title>
        <meta name="description" content="Generated by Liam Idrovo :)" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing></Landing>
    </>
  );
};

export default Home;
