import {
  SignIn,
  SignUp,
  SignedOut,
  UserButton,
  UserProfile,
  useAuth,
  useUser,
} from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Landing from "~/components/PageComponents/Landing";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { getToken, userId } = useAuth();
  const { user } = useUser();

  return (
    <>
      <Head>
        <title>Spotify Huddles</title>
        <meta name="description" content="Generated by Liam Idrovo :)" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserButton></UserButton>

      <Landing></Landing>
    </>
  );
};

export default Home;
